options:
    prevLabel: "<"
    nextLabel: ">"
    doneLabel: "✓"
    exitOnOverlayClick: false
    exitOnEsc: false
    disableInteraction: true
tours:
    index:
        steps:
            nav:
                element: document.querySelector("#navigation-bar")
        next_page: storage.html
    storage:
        steps:
            create:
                element: document.querySelector("#create")
            items:
                element: document.querySelector("#items")
        next_page: shop.html
    shop: 
        steps:
            products:
                element: document.querySelector("#products")
            itembag:
                element: document.querySelector("#itembag")
            pay:
                element: document.querySelector("#pay")
        next_page: about.html
    about:
        steps:
            startIntro:
                element: document.querySelector("#startIntro")        
